security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 9600000

spring:
  application:
    name: CamaraApiSite

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/c_project?useTimezone=true&serverTimezone=UTC
    username: ${JDBC_USERNAME_LOCALHOST}
    password: ${JDBC_PASSWORD_LOCALHOST}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
